Booldoxer

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -37,8 +37,13 @@ jobs:
         run: |
           curl -O https://dl.google.com/chrome-remote-desktop/chromeremotedesktop.dmg
           hdiutil attach chromeremotedesktop.dmg
-          mounted_volume_path=$(ls -d /Volumes/Chrome\ Remote\ Desktop/* | head -n 1)
-          sudo installer -package "$mounted_volume_path/Chrome Remote Desktop.pkg" -target /
+          mounted_volume_path="/Volumes/Chrome Remote Desktop"
+          if [ -d "$mounted_volume_path" ]; then
+            sudo installer -package "$mounted_volume_path/Chrome Remote Desktop.pkg" -target /
+          else
+            echo "Error: Chrome Remote Desktop volume not found"
+            exit 1
+          fi
           hdiutil detach "$mounted_volume_path"
           rm chromeremotedesktop.dmg
         shell: bash
